### ISSUE TITLE
Issue when managing private DNS zone

### ISSUE THREAD

**Issue by jpuchois** [octodns/octodns-azure#47]
Hey,

We are trying to manage our private DNS zone with octo.

We already have created our main private zone on Azure which looks like env.cloudprovider.company.internal.

Our problem is when we create a record using this module. It create a complete new DNS Zone (and not a private one) which looks like record.env.cloudprovider.company.internal instead of using the existing private zone

Are we doing something wrong or the module just don't support private DNS zone ?

Thanks

**Comment by ross** [comment]
Hrm. I'm not familiar with private zones/dns in Azure. Looks like it may be a fairly new feature (GA) https://azure.microsoft.com/en-us/blog/announcing-azure-dns-private-resolver-general-availability/#:~:text=Azure%20Private%20DNS%20manages%20and,Azure%2Dprovided%20names%20during%20deployment.

It looks like they're a completely different resource as far as Azure is concerned. When I go to private DNS in the portal I have no zones, even though I have a number of them over in the original/public DNS resource page. 

<img width="1116" alt="Screen Shot 2023-01-24 at 9 48 17 AM" src="https://user-images.githubusercontent.com/12789/214369308-bb5688ba-91fc-43a0-be25-f95feed2f49b.png">

I'm guessing/hoping there's just a flag that needs to be configured in the Azure client libs to tell things to work with private rather than normal DNS zones. If it's that simple then adding support should be straightforward. If it's more involved/a different API then I don't know what would be required.

**Comment by ross** [comment]
Azure is such a pita to work with 😦, looks like it's a completely separate client lib https://learn.microsoft.com/en-us/python/api/overview/azure/private-dns?view=azure-python. 

That said there's a section under the general DNS rest docs https://learn.microsoft.com/en-us/rest/api/dns/ for private DNS, e.g. https://learn.microsoft.com/en-us/rest/api/dns/privatedns/private-zones and there are some parameters in the zone create/update api that only apply to private zones https://learn.microsoft.com/en-us/rest/api/dns/zones/create-or-update?tabs=HTTP. 

I'm not sure that I'm going to have the bandwidth to sort out what's going on with all of this without a specific setup/use-case for it since it'd probably be fairly involved to get the required VNets and associated resources all set up to poke around at it, figure out how it works, and what would be necessary to get it supported.

/cc @viranch may be able to chime in with thoughts, they're generally more familiar with azure

**Comment by maxolodrou** [comment]
Hello Ross, thx for the quick response and thx for links. But just for information private DNS is not really new feature on Azure: https://azure.microsoft.com/en-us/updates/azure-dns-private-zones-is-now-generally-available/ ==> 2019... the link you give in your first post was about private resolver only.
But what I see the article for the python library for Azure DNS private is pretty new.
In our side (with jpuchois) we will try to adapt to permit manage private also and we will send you code update proposal.

**Comment by viranch** [comment]
Yeah private zones use a separate (but similar) API, so out-of-the-box support yet. Code change wise should not be challenging to add support. Like @ross said, setting up the right testing env is involving. As always, contributions very welcome!
